In [1]:
import mysql.connector
import pandas as pd
import os

In [39]:
class mysql_db_helper:
    def __init__(self,data = 'ecomm'):
        database_name = data
        self.create_connection({"database_name":database_name})

    def create_connection(self, data):
        try:
            # refer to understand the connection https://www.red-gate.com/simple-talk/databases/mysql/retrieving-mysql-data-python/
            self.conn = mysql.connector.connect(option_files = '/home/de24/config/mysqldbconnectors.cnf'
                                               #,allow_local_infile=True this is not required all the time
                                               )
            self.conn.database = data['database_name']
            #self.conn.autocommit = True
            self.curr = self.conn.cursor()
            
        except Exception as e:
            raise Exception(f"Error => {e}")
            

    def query_exec(self,query):
        try:
            # One Query at a time
            self.curr.execute(query)          
            # 1. Check success
            print(f"Rows affected: {self.curr.rowcount}")
            # 2. Save the changes
            self.conn.commit() 
            print("Changes committed to the database.")
        except mysql.connector.Error as err:
            # 3. If an error occurs, the execution stops and goes here
            self.conn.rollback()
            # print(f"Error => {err}")
            raise Exception(f"Error => {err}")

    def query_exec_getresult(self,query):
        try:
            result_df = pd.read_sql(query, self.conn) # reading in Pandas Data frame
        except Exception as e:
            #raise Exception(f"Error => {e}")
            print(f"Error => {e}")
            return -1
        return result_df

    def connection_close(self):
        self.conn.close()

    def __del__(self):
        self.conn.close()

In [ ]:
## customer
mysql_obj = mysql_db_helper('ecomm')

mysql_obj.query_exec(f'''
INSERT INTO ecomm.metadata_config (table_name,tbl_query,duration,duration_type) VALUES 
('customer',
'SELECT * FROM ecomm.customer 
WHERE customer_id in (
    SELECT customer_id 
    FROM orders  
    WHERE YEAR(order_purchase_timestamp) = __YEAR__ 
    AND MONTH(order_purchase_timestamp) = __MONTH__
);',
1,'Month');
''')
mysql_obj.connection_close()

In [56]:
mysql_obj = mysql_db_helper('ecomm')
df = mysql_obj.query_exec_getresult(f'''SELECT * FROM ecomm.metadata_config ;''')
mysql_obj.connection_close()
df.head(10)

/tmp/ipykernel_2144/3125177840.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_df = pd.read_sql(query, self.conn) # reading in Pandas Data frame

,table_name,last_extracxt_date,tbl_query,duration,duration_type
0,customer,2016-08-01,SELECT * FROM ecomm.customer \nWHERE customer_...,1,Month
1,orders,2016-08-01,SELECT * \n FROM orders \n WHERE YEAR(o...,1,Month
2,order_items,2016-08-01,SELECT * FROM ecomm.order_items \nWHERE order_...,1,Month
3,order_payments,2016-08-01,SELECT * FROM ecomm.order_payments \nWHERE ord...,1,Month
4,order_reviews,2016-08-01,SELECT * FROM ecomm.order_reviews \nWHERE orde...,1,Month
5,sellers,2016-08-01,SELECT * FROM ecomm.sellers \nWHERE seller_id ...,1,Month

In [25]:
mysql_obj = mysql_db_helper('ecomm')
mysql_obj.query_exec(f'''
DELETE FROM ecomm.metadata_config
WHERE table_name = 'order_items'; ''')
mysql_obj.connection_close()

Rows affected: 2
Changes committed to the database.

In [58]:
mysql_obj = mysql_db_helper('ecomm')
df = mysql_obj.query_exec_getresult(f'''SHOW TABLES;''')
mysql_obj.connection_close()
df.head(10)

/tmp/ipykernel_2144/3125177840.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_df = pd.read_sql(query, self.conn) # reading in Pandas Data frame

                     Tables_in_ecomm
0  Product_category_name_translation
1                           customer
2                        geolocation
3                    metadata_config
4                        order_items
5                     order_payments
6                      order_reviews
7                             orders
8                            sellers

In [22]:
## orders 

mysql_obj = mysql_db_helper('ecomm')

mysql_obj.query_exec(f'''
INSERT INTO ecomm.metadata_config (table_name,tbl_query,duration,duration_type) VALUES 
('orders',
'SELECT * 
    FROM orders  
    WHERE YEAR(order_purchase_timestamp) = __YEAR__ 
    AND MONTH(order_purchase_timestamp) = __MONTH__
',
1,'Month');
''')
mysql_obj.connection_close()

Rows affected: 1
Changes committed to the database.

In [26]:
## order_items 

mysql_obj = mysql_db_helper('ecomm')

mysql_obj.query_exec(f'''
INSERT INTO ecomm.metadata_config (table_name,tbl_query,duration,duration_type) VALUES 
('order_items',
'SELECT * FROM ecomm.order_items 
WHERE order_id in (
    SELECT order_id 
    FROM orders  
    WHERE YEAR(order_purchase_timestamp) = __YEAR__ 
    AND MONTH(order_purchase_timestamp) = __MONTH__
);',
1,'Month');
''')
mysql_obj.connection_close()

Rows affected: 1
Changes committed to the database.

In [28]:
## order_payments 

mysql_obj = mysql_db_helper('ecomm')

mysql_obj.query_exec(f'''
INSERT INTO ecomm.metadata_config (table_name,tbl_query,duration,duration_type) VALUES 
('order_payments',
'SELECT * FROM ecomm.order_payments 
WHERE order_id in (
    SELECT order_id 
    FROM orders  
    WHERE YEAR(order_purchase_timestamp) = __YEAR__ 
    AND MONTH(order_purchase_timestamp) = __MONTH__
);',
1,'Month');
''')
mysql_obj.connection_close()

Rows affected: 1
Changes committed to the database.

In [30]:
## order_reviews

mysql_obj = mysql_db_helper('ecomm')

mysql_obj.query_exec(f'''
INSERT INTO ecomm.metadata_config (table_name,tbl_query,duration,duration_type) VALUES 
('order_reviews',
'SELECT * FROM ecomm.order_reviews 
WHERE order_id in (
    SELECT order_id 
    FROM orders  
    WHERE YEAR(order_purchase_timestamp) = __YEAR__ 
    AND MONTH(order_purchase_timestamp) = __MONTH__
);',
1,'Month');
''')
mysql_obj.connection_close()

Rows affected: 1
Changes committed to the database.

In [54]:
## order_reviews

mysql_obj = mysql_db_helper('ecomm')

mysql_obj.query_exec(f'''
INSERT INTO ecomm.metadata_config (table_name,tbl_query,duration,duration_type) VALUES 
('sellers',
'SELECT * FROM ecomm.sellers 
WHERE seller_id in (
    SELECT seller_id FROM ecomm.order_items 
    WHERE order_id in (
        SELECT order_id 
        FROM orders  
        WHERE YEAR(order_purchase_timestamp) = __YEAR__ 
        AND MONTH(order_purchase_timestamp) = __MONTH__
    )
);',
1,'Month');
''')
mysql_obj.connection_close()

Rows affected: 1
Changes committed to the database.

In [53]:
mysql_obj = mysql_db_helper('ecomm')
df = mysql_obj.query_exec_getresult(f'''SELECT * FROM ecomm.sellers 
WHERE seller_id in (
    SELECT seller_id FROM ecomm.order_items 
    WHERE order_id in (
        SELECT order_id 
        FROM orders  
        WHERE YEAR(order_purchase_timestamp) = 2016 
        AND MONTH(order_purchase_timestamp) = 09
    )
);''')
mysql_obj.connection_close()
df.head(10)

/tmp/ipykernel_2144/3125177840.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_df = pd.read_sql(query, self.conn) # reading in Pandas Data frame

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,1554a68530182680ad5c8b042c3ab563,37580,monte siao,MG
1,ecccfa2bb93b34a3bf033cc5d1dcdc69,81810,curitiba,PR
2,a425f92c199eb576938df686728acd20,81050,curitiba,PR

In [59]:
mysql_obj = mysql_db_helper('ecomm')
df = mysql_obj.query_exec_getresult(f'''SELECT * FROM geolocation;''')
mysql_obj.connection_close()
df.head(10)

/tmp/ipykernel_2144/3125177840.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_df = pd.read_sql(query, self.conn) # reading in Pandas Data frame

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545622,-46.639294,sao paulo,SP
1,1046,-23.546082,-46.644821,sao paulo,SP
2,1046,-23.546129,-46.642952,sao paulo,SP
3,1041,-23.544392,-46.639500,sao paulo,SP
4,1035,-23.541578,-46.641605,sao paulo,SP
5,1012,-23.547762,-46.635361,são paulo,SP
6,1047,-23.546272,-46.641224,sao paulo,SP
7,1013,-23.546923,-46.634266,sao paulo,SP
8,1029,-23.543770,-46.634277,sao paulo,SP
9,1011,-23.547640,-46.636032,sao paulo,SP